### ISSUE TITLE
Doesn't work on Kodi 17.x in Windows

### ISSUE THREAD

**Issue by yamboo-efi** [yamboo-efi/plugin.video.flix2kodi#2]
Works fine on win10 kodi 16, on krypton I have this error some others have to. Did install python for windows, but still the same error.

20:44:13.730 T:8624   ERROR: XFILE::CDirectory::GetDirectory - Error getting
20:44:37.565 T:6860   ERROR: Previous line repeats 9 times.
20:44:37.565 T:6860   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: DLL load failed: The specified module could not be found.
                                            Traceback (most recent call last):
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\addon.py", line 10, in <module>
                                                from resources import general
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\general.py", line 7, in <module>
                                                import add
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\add.py", line 10, in <module>
                                                from resources import library
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\library.py", line 9, in <module>
                                                import get
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\get.py", line 18, in <module>
                                                from resources import connect, video_parser
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\connect.py", line 15, in <module>
                                                from resources import chrome_cookie
                                              File "D:\fe\Kodi\portable_data\addons\plugin.video.flix2kodi\resources\chrome_cookie.p​y", line 16, in <module>
                                                import win32crypt
                                            ImportError: DLL load failed: The specified module could not be found.
                                            -->End of Python script error report<--
20:44:37.630 T:9940   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.flix2kodi/
20:44:37.631 T:9940   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/) failed

**Comment by yamboo-efi** [comment]
For some reason the embedded python interpreter cannot import .pyd files. Tested with differents libs. Maybe an issue in Kodi 17.x embedded python interpreter.
