### ISSUE TITLE
First Time Startup Crash

### ISSUE THREAD

**Issue by Dracrius** [yamboo-efi/plugin.video.flix2kodi#6]
I just found your addon as I just picked up  a bluetooth remote and wanted to  control Netflix with it too. I currently us IE in kiosk mode and was excited to find a new addon since i gave up back in the days of NetfliXBMC  which didnt work well. I tried both the 0.6.8 and current master but both give me the same error  the second I try to launch the addon after  adding my login info. It simply asks me to check the logs. Here I  will post the log  but I will say I have set the browser to internet explorer and don't even have chrom installed but the error does mention something caled chrome_cookie.py which probably shouldn't be starting for IE. 

I am on Windows 7 running Kodi 16.1

`21:41:45 T:5636   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.flix2kodi/
21:41:45 T:5636   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/) failed
21:42:03 T:1108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: DLL load failed: The specified module could not be found.
                                            Traceback (most recent call last):
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\addon.py", line 10, in <module>
                                                from resources import general
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\general.py", line 7, in <module>
                                                import add
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\add.py", line 10, in <module>
                                                from resources import library
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\library.py", line 9, in <module>
                                                import get
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\get.py", line 18, in <module>
                                                from resources import connect, video_parser
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\connect.py", line 15, in <module>
                                                from resources import chrome_cookie
                                              File "C:\Users\R. Giskard\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\chrome_cookie.py", line 16, in <module>
                                                import win32crypt
                                            ImportError: DLL load failed: The specified module could not be found.
                                            -->End of Python script error report<--`

**Comment by Dracrius** [comment]
I just tired installing chrome and using it but I still get the exact same error.

**Comment by yamboo-efi** [comment]
In versión 0.6.8 added support to windows Kodi 17.x. The included library "win32crypt" have been compiled using that version. So, I think that 0.6.8 versión of the plugin, in windows, only works with Kodi 17.x

I suggest you to update Kodi to 17.x version.

**Comment by fangonaut** [comment]
I'm also getting a crash after first install, raspberry pi, LibreELEC krypton 17.3 it crashes then asks if I want to 'refresh the login?'

not sure if it even works on this system or not, i can't figure out how to find the logs since all i have to navigate is the tv remote :/

**Comment by yamboo-efi** [comment]
@fangonaut 
To get the logs, you can connect to rpi from anoter computer
[https://libreelec.wiki/accessing_libreelec](https://libreelec.wiki/accessing_libreelec)

And you can find the log in $HOME/.kodi/temp/kodi.log
[http://kodi.wiki/view/Log_file/Advanced](http://kodi.wiki/view/Log_file/Advanced)
